export const updates = {
    STARTED: 'STARTED',
    PAUSED: 'PAUSED',
    STOPPED: 'STOPPED',
    TIME_LEFT: 'TIME_LEFT',
    DURATION_ADJUSTED: 'DURATION_ADJUSTED',
    TIME_OUT: 'TIME_OUT',
    CLOSED: 'ROOM_CLOSED',
}