export const updates = {
    STARTED: 'STARTED',
    PAUSED: 'PAUSED',
    STOPPED: 'STOPPED',
    CURRENT_TIME: 'CURRENT_TIME',
    DURATION_ADJUSTED: 'DURATION_ADJUSTED',
    TIME_OUT: 'TIME_OUT',
    CLOSED: 'ROOM_CLOSED',
}