export const updates = {
    STARTED: 'STARTED',
    PAUSED: 'PAUSED',
    STOPPED: 'STOPPED',
    TIME_UPDATE: 'TIME_UPDATE',
    DURATION_ADJUSTMENT: 'DURATION_ADJUSTMENT',
    TIMED_OUT: 'TIMED_OUT',
    ROOM_CLOSED: 'ROOM_CLOSED',
}